kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ .Values.app }}-{{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.app }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: system:discovery
  apiGroup: rbac.authorization.k8s.io