---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  #name: volume-provisioner-{{ .AppName }}-{{ .Namespace }}
  name: {{ template "fullname" . }}-dind-volume-provisioner
  labels:
    #app: dind-volume-provisioner-{{ .AppName }}
    app; {{ template "fullname" . }}-dind-volume-provisioner
subjects:
  - kind: ServiceAccount
    #name: volume-provisioner-{{ .AppName }}
    name: {{ template "fullname" . }}-dind-volume-provisioner
    #namespace: {{ .Namespace }}
roleRef:
  kind: ClusterRole
  #name: volume-provisioner-{{ .AppName }}-{{ .Namespace }}
  name: {{ template "fullname" . }}-dind-volume-provisioner
  apiGroup: rbac.authorization.k8s.io
