kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  #name: {{APP_NAME}}-{{NAMESPACE}}-engine
  name: {{ template "fullname" . }}-engine
rules:
  - apiGroups: [""]
    resources: ["pods", "persistentvolumeclaims"]
    verbs: ["get", "create", "delete", "list"]
