---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: volume-provisioner-{{ .Values.app }}-{{ .Release.Namespace }}
  labels:
    app: dind-volume-provisioner-{{ .Values.app }}
subjects:
  - kind: ServiceAccount
    name: volume-provisioner-{{ .Values.app }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: volume-provisioner-{{ .Values.app }}-{{ .Release.Namespace }}
  apiGroup: rbac.authorization.k8s.io
