apiVersion: v1
type: Opaque
kind: Secret
metadata:
  labels:
    app: {{ .Values.app }}
  name: codefresh-certs-server
  namespace: {{ .Release.Namespaces }}
data:
  server-cert.pem: {{ .Values.runner.certificate.cert }}
  server-key.pem: {{ .Values.runner.certificate.key }}
  ca.pem: {{ .Values.runner.certificate.ca }}

