apiVersion: v1
type: Opaque
kind: Secret
metadata:
  labels:
    #app: venona
    app: {{ template "fullname" . }}
  #name: codefresh-certs-server
  name: {{ template "fullname" . }}-codefresh-certs-server
  #namespace: {{NAMESPACE}}
data:
  #server-cert.pem: {{SERVER_CERT_CERT}}
  server-cert.pem: {{ .Values.runner.certificate.cert }}
  #server-key.pem: {{SERVER_CERT_KEY}}
  server-key.pem: {{ .Values.runner.certificate.key }}
  #ca.pem: {{SERVER_CERT_CA}}
  ca.pem: {{ .Values.runner.certificate.ca }}

