apiVersion: v1
type: Opaque
kind: Secret
metadata:
  labels:
    app: {{ .Values.app }}
  name: codefresh-certs-server
  namespace: {{ .Release.Namespace }}
data:
  server-cert.pem: {{ .Values.runner.certificate.cert | quote }}
  server-key.pem: {{ .Values.runner.certificate.key | quote }}
  ca.pem: {{ .Values.runner.certificate.ca | quote }}

