apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  #name: dind-lv-monitor-{{APP_NAME}}
  name: {{ template "fullname" . }}-dind-lv-monitor
  #namespace: {{NAMESPACE}}
  labels:
    #app: dind-lv-monitor
    app: {{ template "fullname" . }}-dind-lv-monitor
spec:
  template:
    metadata:
      labels:
        #app: dind-lv-monitor
        app: {{ template "fullname" . }}-dind-lv-monitor
      annotations:
        prometheus_port: "9100"
        prometheus_scrape: "true"
    spec:
      #serviceAccountName: volume-provisioner-{{APP_NAME}}
      serviceAccountName: {{ template "fullname" . }}-volume-provisioner
      # Debug:       
      # hostNetwork: true
      # nodeSelector:
      #   kubernetes.io/role: "node"
      tolerations:
        - key: 'codefresh/dind'
          operator: 'Exists'
          effect: 'NoSchedule'
      containers:
        - image: codefresh/dind-volume-utils:v5
          name: lv-cleaner
          imagePullPolicy: Always
          command:
          - /bin/local-volumes-agent
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: VOLUME_PARENT_DIR
              value: /var/lib/codefresh/dind-volumes
#              Debug:                  
#            - name: DRY_RUN
#              value: "1"
#            - name: DEBUG
#              value: "1"
#            - name: SLEEP_INTERVAL
#              value: "3"
#            - name: LOG_DF_EVERY
#              value: "60"
#            - name: KB_USAGE_THRESHOLD
#              value: "20"

          volumeMounts:
          - mountPath: /var/lib/codefresh/dind-volumes
            readOnly: false
            name: dind-volume-dir
      volumes:
      - name: dind-volume-dir
        hostPath:
          path: /var/lib/codefresh/codefresh/dind-volumes
