apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.app }}
    version: {{ .Values.runner.image.tag | quote }}
  name: {{ .Values.app }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  revisionHistoryLimit: 5
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Values.app }}
        version: {{ .Values.runner.image.tag | quote }}
    spec:
      serviceAccountName: {{ .Values.app }}
      containers:
      - env:
        - name: SELF_DEPLOYMENT_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: CODEFRESH_TOKEN
          valueFrom:
            secretKeyRef:
              name: {{ .Values.app }}
              key: codefresh.token
        - name: CODEFRESH_HOST
          value: {{ .Values.runner.api.host }}
        - name: AGENT_MODE
          value: {{ .Values.runner.mode}}
        - name: AGENT_NAME
          value: {{ .Values.app }}
        image: {{ .Values.runner.image.repository }}:{{ .Values.runner.image.tag }}
        imagePullPolicy: Always
        name: {{ .Values.app }}
      restartPolicy: Always
