apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dind-volume-provisioner-{{ .Values.app }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: dind-volume-provisioner
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: dind-volume-provisioner
    spec:
      serviceAccount: volume-provisioner-{{ .Values.app }}
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
        operator: "Exists"
      containers:
      - name: dind-volume-provisioner
        image: {{ .Values.volume.image.repository}}:{{ .Values.volume.image.tag }}
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "300m"
            memory: "400Mi"
          limits:
            cpu: "1000m"
            memory: "6000Mi"
        command:
          - /usr/local/bin/dind-volume-provisioner
          - -v=4
          - --resync-period=50s          
        env:
        - name: PROVISIONER_NAME
          value: codefresh.io/dind-volume-provisioner-{{ .Values.app }}-{{ .Release.Namespace }}
       