---
apiVersion: v1
kind: Service
metadata:
  labels:
    #app: dind
    app: {{ template "fullname" . }}-dind
  #name: dind
  name: {{ template "fullname" . }}-dind
  #namespace: {{ .Namespace }}
spec:
  ports:
  - name: "dind-port"
    port: 1300
    protocol: TCP

  # This is a headless service, Kubernetes won't assign a VIP for it.
  # *.dind.default.svc.cluster.local
  clusterIP: None
  selector:
    #app: dind
    app: {{ template "fullname" . }}-dind

