kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  #name: {{APP_NAME}}
  name: {{ template "fullname" . }}
  #namespace: {{NAMESPACE}}
rules:
- apiGroups: [""]
  resources: ["pods", "persistentvolumeclaims"]
  verbs: ["get", "create", "delete"]
