apiVersion: v1
kind: Secret
type: Opaque
metadata:
  #name: {{APP_NAME}}
  name: {{ template "fullname" . }}
  #namespace: {{NAMESPACE}}
data:
  #codefresh.token: {{API_TOKEN_BASE64}}
  codefresh.token: {{ .Values.runner.api.token | b64enc }}