---
apiVersion: v1
kind: ServiceAccount
metadata:
  #name: volume-provisioner-{{APP_NAME}}
  name: {{ template "fullname" . }}-dind-volume-provisioner
  #namespace: {{NAMESPACE}}
  labels:
    #app: dind-volume-provisioner
    app: {{ template "fullname" . }}-dind-volume-provisioner
