---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  #name: dind-local-volumes-{{APP_NAME}}-{{NAMESPACE}}
  name: {{ template "fullname" . }}-dind-local-volumes
  labels:
    #app: dind-volume-provisioner
    app: {{ template "fullname" . }}-dind-volume-provisioner
#provisioner: codefresh.io/dind-volume-provisioner-{{APP_NAME}}-{{NAMESPACE}}
provisioner: codefresh.io/{{ template "fullname" . }}-dind-volume-provisioner
parameters:
  volumeBackend: local
